//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using UnityEngine;
using System;

public class ObjectPool : MonoBehaviour
{
	public GameObject asteroidPrefab;
	public GameObject asteroidPrefab2;
	public GameObject asteroidPrefab3;
	public GameObject asteroidPrefab4;
	public GameObject asteroidPrefab5;

	private List<GameObject> pool;
	private List<Boolean> isFree;
	private GameObject[] prefabs;

	void Awake()
	{
		pool = new List<GameObject>();
		isFree = new List<Boolean>();
		prefabs = new GameObject[5] {asteroidPrefab, asteroidPrefab2, asteroidPrefab3, asteroidPrefab4, asteroidPrefab5};
	}

	void Start()
	{
		// Don't put things here - other classes need to use this class during start, so things need to be set up using Awake()
	}

	void Update()
	{
		Debug.Log(pool.Count);
	}

	public int addBody(float x, float y, float depth, float mass)
	{
		int nextFree = 0;
		while(nextFree < isFree.Count && !(isFree[nextFree] || !pool[nextFree].activeSelf)) nextFree++;
		if(nextFree == pool.Count)
		{
			GameObject asteroid = (GameObject)Instantiate(pickAPrefab(prefabs), new Vector3(x, y, depth), Quaternion.identity);
			Body asteroidScript = asteroid.GetComponent<Body>();
			asteroidScript.mass = mass;
			pool.Add(asteroid);
			isFree.Add(false);
			return nextFree;
		}
		GameObject a = pool[nextFree];
		a.rigidbody2D.transform.position = new Vector3(x, y, depth);
		Body aScript = a.GetComponent<Body>();
		aScript.mass = mass;
		a.SetActive(true);
		isFree[nextFree] = false;
		return nextFree;
	}

	public GameObject getBody(int index)
	{
		return pool[index];
	}

	public void removeBody(int index)
	{
		pool[index].SetActive(false);
		isFree[index] = true;
	}

	public void drain()
	{
		for(int i = 0; i < pool.Count; i++) removeBody(i);
	}

	private GameObject pickAPrefab(GameObject[] objs)
	{
		int num = objs.Length;
		int pick = Mathf.FloorToInt(UnityEngine.Random.Range (0, num));
		return objs[pick];
	}
}

